import {
  SANDTEST_URL,
  RECIEPT_VALIDATE_URL,
  IN_APP_PURCHASE_KEY,
  IN_APP_PURCHASE_PASSWORD,
  PRIVACY_POLICY,
  TERMS_AND_CONDITIONS,
  MESSENGER_URL,
  DATABASE_NAME,
} from '@env';

const devenvs = {
  SANDTEST_URL,
  RECIEPT_VALIDATE_URL,
  IN_APP_PURCHASE_KEY,
  IN_APP_PURCHASE_PASSWORD,
  PRIVACY_POLICY,
  TERMS_AND_CONDITIONS,
  MESSENGER_URL,
  DATABASE_NAME,
};
const prodenvs = {
  SANDTEST_URL,
  RECIEPT_VALIDATE_URL,
  IN_APP_PURCHASE_KEY,
  IN_APP_PURCHASE_PASSWORD,
  PRIVACY_POLICY,
  TERMS_AND_CONDITIONS,
  MESSENGER_URL,
  DATABASE_NAME,
};

export default __DEV__ ? devenvs : prodenvs;
